import { v4 as uuid } from 'uuid';

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    img: 'https://geektech.me/wp-content/uploads/2020/03/2b3324f367d76e5d988a4418249aeac5.png',
    name: 'Samsung M10',
    rating: 5,
    price: 40000,
    discountedPrice: 30000,
    topProduct: true,
    categoryName: 'mobile-phones',
  },
  {
    _id: uuid(),
    img: 'https://i.gadgets360cdn.com/products/large/1519585124_635_samsung_galaxy_s9_blue.jpg?downsize=*:180',
    name: 'Samsung M31',
    rating: 4,
    price: 20000,
    discountedPrice: 15000,
    topProduct: false,
    categoryName: 'mobile-phones',
  },
  {
    _id: uuid(),
    img: 'https://images.samsung.com/is/image/samsung/p5/hk/news/npseries_3.jpg?$ORIGIN_JPG$',
    name: 'Samsung notebook',
    rating: 3,
    price: 30000,
    discountedPrice: 25000,
    topProduct: false,
    categoryName: 'laptops',
  },
  {
    _id: uuid(),
    img: 'https://m.media-amazon.com/images/I/51FWf+esWHL._AC_SX679_.jpg',
    name: 'Mackbook',
    rating: 5,
    price: 60000,
    discountedPrice: 55000,
    topProduct: true,
    categoryName: 'laptops',
  },

  {
    _id: uuid(),
    img: 'https://i.gadgets360cdn.com/products/laptops/large/1546452955_635_dell_inspiron-3567.jpg?downsize=*:180',
    name: 'Dell inspiron',
    rating: 3,
    price: 24000,
    discountedPrice: 20000,
    topProduct: false,
    categoryName: 'laptops',
  },
  {
    _id: uuid(),
    img: 'https://d28wu8o6itv89t.cloudfront.net/images/Realmeipng-1588598003732.png',
    name: 'RealMe',
    rating: 3,
    price: 15000,
    discountedPrice: 10000,
    topProduct: false,
    categoryName: 'mobile-phones',
  },
  {
    _id: uuid(),
    img: 'https://static.toiimg.com/thumb/resizemode-4,msid-88473035,width-800,height-450,ver-75/88473035.jpg',
    name: 'Boat earphones',
    rating: 5,
    price: 1000,
    discountedPrice: 800,
    topProduct: true,
    categoryName: 'earphones',
  },
  {
    _id: uuid(),
    img: 'https://webobjects2.cdw.com/is/image/CDW/4426092?$product-detail$',
    name: 'Nokia stereo',
    rating: 2,
    price: 600,
    discountedPrice: 400,
    topProduct: false,
    categoryName: 'earphones',
  },
  {
    _id: uuid(),
    img: 'https://img.us.news.samsung.com/us/wp-content/uploads/2021/08/03131111/Galaxy-Tab-S7_FE_MysticBlack_Front-1536x1024.jpg',
    name: 'Samsung S7',
    rating: 4,
    price: 15000,
    discountedPrice: 10000,
    topProduct: true,
    categoryName: 'tabs',
  },
  {
    _id: uuid(),
    img: 'https://cdn1.smartprix.com/rx-ifuspObh9-w240-h290/lenovo-tab-m10.webp',
    name: 'Lenovo M10',
    rating: 5,
    price: 10000,
    discountedPrice: 8000,
    topProduct: false,
    categoryName: 'tabs',
  },
];
